### ISSUE TITLE
root4star/St_geant_Maker deadlocks on SIGSEGV in malloc

### ISSUE THREAD

**Issue by veprbl** [star-bnl/star-sw#137]
I found some jobs sleeping with the following backtrace:

```C++
#0  0x55636430 in __kernel_vsyscall ()
#1  0x5845bdc2 in __lll_lock_wait_private () from /lib/libc.so.6
#2  0x583d1cc5 in _L_lock_13657 () from /lib/libc.so.6
#3  0x583cf181 in malloc () from /lib/libc.so.6
#4  0x580a93f5 in ?? () from /lib/libgfortran.so.3
#5  0x58149b3a in ?? () from /lib/libgfortran.so.3
#6  0x58158290 in ?? () from /lib/libgfortran.so.3
#7  0x087265ca in traceq (lunp=@0xffdb195c: 0, lev=@0xffdb1958: 99)
    at /build/LCG/work/cernlib/2006/src/packlib/kernlib/kerngen/tcgen/traceq.F:25
#8  0x0868d0e5 in signal_handler (sig=11) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kienbr.c:182
#9  <signal handler called>
#10 0x583cb708 in malloc_consolidate () from /lib/libc.so.6
#11 0x583cc289 in _int_free () from /lib/libc.so.6
#12 0x5829897f in operator delete(void*) () from /lib/libstdc++.so.6
#13 0x590cbe8d in StMemoryPool::~StMemoryPool (this=0x5f4e3b30 <StTpcHit::mPool>, __in_chrg=<optimized out>)
    at .sl73_gcc485/obj/StRoot/StarClassLibrary/StMemoryPool.cc:33
#14 0x58388669 in __run_exit_handlers () from /lib/libc.so.6
#15 0x583886cd in exit () from /lib/libc.so.6
#16 0x5589644a in TUnixSystem::Exit (this=0x9c62250, code=0, mode=true) at core/unix/src/TUnixSystem.cxx:1987
#17 0x57272e61 in TRint::Terminate (this=0x9ca6fb8, status=0) at core/rint/src/TRint.cxx:598
#18 0x57274174 in TRint::Run (this=0x9ca6fb8, retrn=false) at core/rint/src/TRint.cxx:385
#19 0x080946e3 in main (argc=1, argv=0xffdb4af4) at .sl73_gcc485/obj/asps/rexe/MAIN_rmain.cxx:32
```

The `traceq` is a part of kumac's signal handler. It's only implemented for HP-UX and VAX.
https://github.com/apc-llc/cernlib/blob/master/2006/src/packlib/kernlib/kerngen/tcgen/traceq.F
Specifically the line 25 is an innocent write https://github.com/apc-llc/cernlib/blob/6e32ba8132318864a244021366708ddbdbebf8ea/2006/src/packlib/kernlib/kerngen/tcgen/traceq.F#L25
However inside the GNU Fortran runtime library is tries to malloc, which in turn tries to acquire a lock on a mutex, which is a big no-no to do in a signal handler (they come asynchronously and if mutex is already locked, all threads will deadlock if signal handler tries to lock it again).

## Steps to reproduce ##
I don't have a reproducer for the deadlock (that probably requires setting a crash in the memory allocator), but I know why the signal handler is hijacked.
```c++
# cat bug.C
void bug(int do_segfault=0) {
   gROOT->LoadMacro("bfc.C");
   Load();
   StChain *chain = new StChain("foo");
   bfc(-1, "gstar", NULL);
   chain->Init();
   if (do_segfault) {
     int *i = NULL;
     *i;
   }
}
```

This prints the familiar message:
```c++
# csh -c "starver SL21c; root4star -l -b -q bug.C'(1)'"
<snip>
 *** Break *** Segmentation violation
 Traceq lun = 0, level = 99 

 TRACEQ.  In-line trace-back still not available.
Signal 11 caught without longjmp target
```

After looking at the cernlib's code, it appears that `ku_trap` is responsible for setting the handler
( https://github.com/apc-llc/cernlib/blob/master/2006/src/packlib/kuip/code_kuip/kienbr.c#L446 )

```c++
# cat bug.gdb 
break main
run
break ku_trap
continue
backtrace
# csh -c "starver SL21c; gdb --batch --command bug.gdb --args root4star -l -b -q bug.C"
<snip>
Breakpoint 2, ku_trap (enable=1, traceback=0) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kienbr.c:448448     /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kienbr.c: No such file or directory.
#0  ku_trap (enable=1, traceback=0) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kienbr.c:448#1  0x08682c38 in kxbreak () at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kienbr.c:652
#2  0x08681f92 in do_action (cmd=<optimized out>) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kexec.c:1471
#3  call_action (cmd=0x8bd5e80 <_KUIP_SET_SHOW_BREAK.1632>) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kexec.c:1508
#4  0x0868222b in exec_decoded_cmd (cmd=0x8bd5e80 <_KUIP_SET_SHOW_BREAK.1632>) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kexec.c:1342#5  0x08681a74 in fill_arg_list (block_panel=<optimized out>, display_panel=<optimized out>, want_prompt=<optimized out>, arg_line=<optimized ou
t>, cmd=<optimized out>) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kexec.c:1262#6  exec_single_cmd (block_panel=<optimized out>, display_panel=<optimized out>, interactive=<optimized out>, cmd_line=<optimized out>) at /buil
d/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kexec.c:466
#7  exec_multiple_cmds (cmd_string=<optimized out>, interactive=1, display_panel=0x0) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip
/kexec.c:276
#8  0x08681cc6 in exec_cmd_string (cmd_string=0x89e4c14 "/KUIP/SET_SHOW/BREAK !", interactive=1, display_panel=0x0) at /build/LCG/work/cernlib/2
006/src/packlib/kuip/code_kuip/kexec.c:211#9  0x08681d4a in ku_exel (cmd_string=0x89e4c14 "/KUIP/SET_SHOW/BREAK !") at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kexec.c:168
5#10 0x086902f0 in kuinit_ (nwords=0xfffa1240) at /build/LCG/work/cernlib/2006/src/packlib/kuip/code_kuip/kuinit.c:199
#11 0x084c1683 in pawint2 (nwpaws=@0x8958888: 0, choptt=..., pgexi=0x81b0774 <agpawe>, iwtyp=@0x8fa7ec4: 0, _choptt=2) at /build/LCG/work/cernlib/2006/src/pawlib/paw/code/pawint2.F:131
#12 0x081af77e in master.0.aginit (__entry=0) at .sl73_gcc485/obj/asps/Simulation/starsim/atmain/agmain.F:198#13 0x081ae4db in aginit () at .sl73_gcc485/obj/asps/Simulation/starsim/atmain/agmain.F:61
#14 0x080c533e in TGiant3::Aginit (this=0xf0fe7e0, command=0xeeb4fe0 " -g 10 -p 0 -w 0") at .sl73_gcc485/obj/asps/rexe/TGeant3/TGiant3.cxx:3697#15 0x080c5080 in TGiant3::Aginit (this=0xf0fe7e0, nwgeant=@0xfffa1538: 10, nwpaw=@0xfffa153c: 0, iwtype=@0xfffa1540: 0) at .sl73_gcc485/obj/asp
s/rexe/TGeant3/TGiant3.cxx:3645#16 0x080c14d6 in TGiant3::TGiant3 (this=0xf0fe7e0, title=0xf1c134fe "C++ Interface to Geant3", nwgeant=10, nwpaw=0, iwtype=0) at .sl73_gcc485/o
bj/asps/rexe/TGeant3/TGiant3.cxx:538#17 0xf1bddc27 in St_geant_Maker::Init (this=0xf0f3d88) at .sl73_gcc485/obj/StRoot/St_geant_Maker/St_geant_Maker.cxx:895
#18 0xf3bc7b98 in StMaker::Init (this=0xeeba8d0) at .sl73_gcc485/obj/StRoot/StChain/StMaker.cxx:703
#19 0xf3bc1ca3 in StChain::Init (this=0xeeba8d0) at .sl73_gcc485/obj/StRoot/StChain/StChain.cxx:105
#20 0xf3aac430 in StBFChain::Init (this=0xeeba8d0) at .sl73_gcc485/obj/StRoot/StBFChain/StBFChain.cxx:1031
<snip>
```

Turns out this is a documented behaviour for `/KUIP/SET_SHOW/BREAK`: http://www.hep.vanderbilt.edu/~focuser/reference_manual/KUIP_SET_SHOW.html

**Comment by veprbl** [comment]
A workaround for this is
```C++
St_geant_Maker *geantMaker = dynamic_cast<St_geant_Maker*>(chain3->GetMakerInheritsFrom("St_geant_Maker"));
geantMaker->Do("/KUIP/SET_SHOW/BREAK OFF");
```

Naturally, I still see the crashes with this, as the underlying problem is not resolved.
But I also see some occasional deadlocks like this
```C++
(gdb) bt
#0  0x5557f430 in __kernel_vsyscall ()
#1  0x583a4dc2 in __lll_lock_wait_private () from /lib/libc.so.6
#2  0x5831aa4e in _L_lock_5056 () from /lib/libc.so.6
#3  0x583150c1 in _int_free () from /lib/libc.so.6
#4  0x55edec9b in G__close_inputfiles () at cint/cint/src/scrupto.cxx:1171
#5  0x557cab58 in TCint::~TCint (this=0xb1bfb90, __in_chrg=<optimized out>) at core/meta/src/TCint.cxx:229
#6  0x5571b2f9 in TROOT::~TROOT (this=0x55caa060 <ROOT::GetROOT()::root>, __in_chrg=<optimized out>) at core/base/src/TROOT.cxx:549
#7  0x582d19da in __cxa_finalize () from /lib/libc.so.6
#8  0x556bfae4 in __do_global_dtors_aux () from /afs/rhic.bnl.gov/star/ROOT/5.22.00/.sl73_gcc485/rootdeb/lib/libCore.so
#9  0x55b78b40 in _fini () from /afs/rhic.bnl.gov/star/ROOT/5.22.00/.sl73_gcc485/rootdeb/lib/libCore.so
#10 0x5556d21a in _dl_fini () from /lib/ld-linux.so.2
#11 0x582d1669 in __run_exit_handlers () from /lib/libc.so.6#12 0x582d16cd in exit () from /lib/libc.so.6#13 0x557df44a in TUnixSystem::Exit (this=0xb1bd250, code=0, mode=true) at core/unix/src/TUnixSystem.cxx:1987
#14 0x571bbe61 in TRint::Terminate (this=0xb201fb8, status=0) at core/rint/src/TRint.cxx:598
#15 0x571bd174 in TRint::Run (this=0xb201fb8, retrn=false) at core/rint/src/TRint.cxx:385
#16 0x080946e3 in main (argc=1, argv=0xffa6b7a4) at .sl73_gcc485/obj/asps/rexe/MAIN_rmain.cxx:32
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x58723980 (LWP 51914) "root4star" 0x5557f430 in __kernel_vsyscall ()
```
And I don't understand how this one can happen.
